stefanpenner/es6-promise

- .spmignore
- package.json
A nicer package manager: http://spmjs.io
Documentation: http://spmjs.io/documentation
http://spmjs.io/package/snabbt.js
---
It is a browser-side package manager popular in China, suppling a complete lifecycle managment of package via [spm](https://github.com/spmjs/spm/tree/master).
> If you need ownership of snabbt.js in spmjs, I can add it for your account after signing in http://spmjs.io.
spmjs/spm#781
> support spm

- lib/es6-promise/polyfill.js
This is improved version of #80.
This changes nothing when the environment is browser or node.js, and makes polyfill work in the environments in which global object is unnamed and Function constructor is available, such as Titanium Mobile or rhino. This also makes polyfill throw when the envrionment isn't browser nor node.js and Function constructor is unavailable because of CSP restriction. (I believe this makes sense.)
Thanks,
> Add support of polyfill() for some more environments

- lib/es6-promise/-internal.js
fix #101 
This is only syncing a commit from [rsvp](https://github.com/tildeio/rsvp.js/pull/333), credits to @teddyzeenny for the original changes
> Follow thenable state not own state

- lib/es6-promise/promise.js
For context:
-https://github.com/thlorenz/exorcist/issues/17
-https://github.com/freedomjs/freedom/issues/276
Really one should be allowed to use unicode apostrophes in source code if they want, but since there's no harm sticking to ascii and it smoothes out build processes I decided to create a pull request for your consideration. Thanks!
> ascii character for apostrophe (makes sourcemaps happier)

- .travis.yml
This change enables to use the container based infrastructure on travis-ci and must speed up the build.
http://docs.travis-ci.com/user/workers/container-based-infrastructure/
Thanks,
> Use container based infrastructure on travis-ci

- Brocfile.js
This closes #142 
The default values for `mangle` and `compress` options seem to be `false`. (The readme of broccoli-uglify-js is confusing and they have a issue for that ( https://github.com/joliss/broccoli-uglify-js/pull/9 ) ).
This setting reduces the build size from 17,952 bytes to 6,408 bytes.
Thanks,
> Mangle and compress the minified version

- README.md
This PR updates the `README.md` with details about PhantomJS requirement for running tests.
Not having PhantomJS installed under newer node versions, was the cause of #160 reported by me yesterday, once installed, all was well.
> Update README.md with details about PhantomJS requirement for running tests

- lib/es6-promise/enumerator.js
The function `isArray` is imported but not used. On IE 8, the method
`Array.isArray` doesn't exist and we get an error.
> IE8: use isArray.

- README.md
seems the libs were moved to `dist/lib/*` instead of `dist/*`
> Update Broken Links in README.md

- lib/es6-promise/asap.js
Caching a reference to the global setTimeout is necessary to be compatible with test libraries that fake time, like sinon.js
See https://github.com/taylorhakes/promise-polyfill/pull/15
> Increase compatiblity with faking time in test tools

- lib/es6-promise/polyfill.js
Hi everyone,
this is a fix for the [WebMAF framework](http://develop.scee.net/research-technology/), used for Playstation web apps development.
Their Promise implementation made impossible to call Promise.resolve() **without** a parameter. Therefore the app would crash with a "_TypeError: expecting at least one argument_" when executing those [3 lines](https://github.com/stefanpenner/es6-promise/blob/ad25a4b7a13e7724c8e3767b75df2660878da913/lib/es6-promise/polyfill.js#L21-L23).
So, I basically wrapped the second condition in a try/catch in order to call the resolve method safely. The error is currently silently ignored, as I don't think anything should be done at this point.
> Supporting polyfill for WebMAF

- auto.js
- package.json
* `auto.js` was not being published to NPM
* `require('.')` doesn't work on Node < 4
Fixes #238.
> Fix auto.js polyfill

- auto.js
Trying this again since the [last PR](https://github.com/stefanpenner/es6-promise/pull/239) got rekt...
* `require('.')` doesn't work on Node < 4
> Fix auto.js for Node < 4 compatibility

- .travis.yml
- yarn.lock
I had doubted that this had something to do with yarn.
I got the error to reproduce locally.
Did something like `git bisect` manually first.
Then just 
```sh
rm yarn.lock
yarn
yarn test
```
And then the error went away.
So I speculate the problem is that greenkeeper-bot updates package.json but it does not update yarn.lock file. Which then makes our tests run on older versions of packages even though they are updated in package.json.
So I think the solution would be that if we are using yarn to run our tests in travis, we need to update yarn.lock file when greenkeeper updates our package.json.
> Fix Node v4 Tests

- package.json
This package *should* show up in this search: https://www.npmjs.com/search?q=promise%20polyfill
> fix npm SEO for 'promise polyfill'

- README.md
http://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise-constructor -> http://www.ecma-international.org/ecma-262/6.0/#sec-promise-constructor
Because http://people.mozilla.org/~jorendorff/es6-draft.html#sec-promise-constructor is broken
> Update ES6 Promise link at Readme

- package.json
because `prepublish` is run on `npm install` also.
To make a production package on publishing to npm, `prepublishOnly` is better hook to do that.
https://docs.npmjs.com/misc/scripts#prepublish-and-prepare
> Prefer prepublishOnly to prepublish

- lib/es6-promise/enumerator.js
I noticed that the `validationError` function [is declared twice](https://github.com/stefanpenner/es6-promise/blob/4abbe5edc6afb575ce8c3d03338eb7a15528e23e/lib/es6-promise/enumerator.js#L23-L29):
```js
function validationError() {
return new Error('Array Methods must be provided an Array');
}
function validationError() {
return new Error('Array Methods must be provided an Array');
};
```
This PR removes one of the two function declarations.
> Remove duplicate "validationError" function

- lib/es6-promise/-internal.js
- lib/es6-promise/enumerator.js
Remove try/catch avoidance hacks, as modern runtimes handle this correctly. (as per @bmeurer's suggestion)
> Remove try/catch avoidance hacks

- lib/es6-promise/asap.js
In order to solve problems, described in issue stefanpenner#350
> Use setTimeout(0)
